### ISSUE TITLE
Inklusionszeugnisse de la Haye

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Zeugnisse-NRW#22]
Man sollte vielleicht die Inklusionszeugnisse auf das neue Memo-Feld individuelle Förderbemerkung umstellen.

In dem Ordner sind auch die neuen Lernstandsberichte und Inklusionszeugnisse von Herrn Richter.
Die haben das eingebaut.

**Comment by mueller-falko** [comment]
Ich habe die Zeugnisse umgestellt. Allerdings ist mir aufgefallen, dass in den normalen Halbjahreszeugnissen zum Teil sehr ausführliche automatische Texte erzeugt wurden, die ja jetzt raus sind. Da sollte man beim Release einen deutlichen Hinweis drauf geben, damit die bisherigen Nutzer nicht irritiert sind.

**Comment by FPfotenhauer** [comment]
Wir machen einen Hinweis in der Versiongeschichte.
