### ISSUE TITLE
Abschlusszeugnisse Fußnote 4

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Zeugnisse-NRW#24]
In einigen Abschlusszeugnissen ist die Fußnote 4 beim GeR im Ausdruck verutscht, so dass Sie den Doppelpunkt "berührt".

Gemeldet für das GE-HA10-Zeugnis.

Wir sollten aber alle kurz kontrollieren.

**Comment by mueller-falko** [comment]
Alle Abschluss- und Abgangszeugnisse überprüft und ggfs. angepasst.
