### ISSUE TITLE
Fehler Sek1

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Zeugnisse-NRW#33]
https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?p=13553#p13553

Wir müssten mal prüfen, ob der Kollege Recht hat.

**Comment by mueller-falko** [comment]
Er hat Recht. Mögliche Lösung:
im Subreport UnterschriftenDatum folgendes Ändern:
1)
procedure La_SchulleitungOnGetText:
Den Eintrag "SchuelerKlasse['AbteilungsleiterKrz']" ersetzen durch "Lernabschnitte['AbteilungsleiterKrz']"
2)
procedure DetailBeforePrint
La_Klassenleitung_Stv.Visible := (UnterschriftenMitStvKlassenlehrer) AND (Lernabschnitte['StvKLNachname']<>'');

**Comment by mueller-falko** [comment]
Hab es gerade mal getestet. 1) funktioniert nicht. Offenbar werden die Abteilungsleiter nicht Abschnittsweise gespeichert, obwohl sie in der Datenquelle drinstehen. Hab aber auch keine andere Idee.
2) funktioniert.

**Comment by FPfotenhauer** [comment]
Ich habe gerade mal in die Lernabschnitte geschaut, die werden tatsächlich nicht gespeichert.
Vermutlich holt die Datenquelle sich das einfach aus der Tabelle Abteilungen.
Dann kann der Fehler momentan nicht behoben werden. Das andere klappt ja....

**Comment by mueller-falko** [comment]
... muss aber noch in allen Zeugnissen geändert werden. War vielleicht etwas voreilig, das issue zu schließen.

**Comment by FPfotenhauer** [comment]
Auch der Abteilungsleiter kann noch geändert werden.

**Comment by M-Plu** [comment]
Hallo Frank, was meinst du mit deinem letzten Betrag?

Für mich klingt das noch einem Fehler in Schild, was die Speicherung der Abteilungsleiter betrifft. Habe ich das richtig verstanden?

**Comment by mueller-falko** [comment]
Ich habe nochmal ausführlicher getestet. Wenn ein Schüler z.B. von der 7 in die 8 kommt und dabei die Abteilung wechselt, wird beim Druck aus dem letzten Schuljahr bei Verwendung von "SchuelerKlasse" der Abteilungsleiter des aktuellen Jahres (8) genommen. Wenn man "Lernabschnitte" benutzt, wird korrekt der Abteilungsleiter des letzten Jahres (7) benutzt.
Wenn man hingegen im aktuellen Abschnitt einen neuen Abteilungsleiter z.B. für 8-10 einträgt, und für einen aktuellen 9er Schüler das Zeugnis aus dem letzten Abschnitt druckt, erscheint immer der neue Abteilungsleiter, egal welche Quelle man nimmt.

**Comment by mueller-falko** [comment]
Das gleiche Problem tritt übrigens auf, wenn der Schulleiter wechselt. Solange das Zeugnis auf den Eintrag aus der DB zugreift, wird immer der aktuelle Schulleiter ausgegeben. Das könnte man nur dann abfangen, wenn die tatsächlichen Namen im Lernabschnitt gespeichert würden.
Wie auch immer, ich schlage vor, dass ich beide Änderungen aus meinem ersten Post in die Zeugnisse einbaue. So oder so ist es eine Verbesserung.

**Comment by M-Plu** [comment]
Die Änderungen würde ich auch einpflegen. Der Rest müsste in Schild gefixt werden.

**Comment by FPfotenhauer** [comment]
In Schild-NRW wird momentan nichts "gefixt", dann bleibt das so, wie es seit 20 Jahren ist....

**Comment by mueller-falko** [comment]
Habe die Änderungen in allen Zeugnissen eingepflegt.
